---
title: 'Data Science - Homework #2'
author: "Jon Brock - JPB2210"
output: 
    github_document:
        toc: TRUE
        toc_depth: 2
---

```{r load_packages, include = FALSE}
library(tidyverse)
library(readxl)
```

## Problem #1
###### (*25 points*)
##### *Read and clean the Mr. Trash Wheel sheet:*

```{r read_in_mr_trash_wheel_data}
#THIS CODE WORKS! DO NOT CHANGE IT!
mr_tw_df =
    read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "Mr. Trash Wheel", skip = 1) %>% 
    janitor::clean_names() %>% 
    select(-x15) %>% 
    drop_na(dumpster)

view(mr_tw_df)
```

```{r read_in_2017_precipitation data}
#THIS CODE WORKS! DO NOT CHANGE IT!
precip_2017 =
    read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2017 Precipitation", skip = 1) %>%
    janitor::clean_names() %>% 
    drop_na(month) %>% 
    mutate(year = "2017")
```

```{r read_in_2018_precipitation data}
#THIS CODE WORKS! DO NOT CHANGE IT!
precip_2018 =
    read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2018 Precipitation", skip = 1) %>%
    janitor::clean_names() %>% 
    drop_na() %>% 
    mutate(year = "2018")
```

## Problem #2
###### (*25 points*)
##### *Read and Merge 538.com Datasets:*


## Problem #3
###### (*25 points*)
##### *BABY NAMES! BABY NAMES! BABY NAMES!:*